# Generated by Django 5.0.1 on 2026-01-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AddField(
            model_name='school',
            name='academic_calendar',
            field=models.CharField(default='January - December', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='class_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='has_computer_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_laboratory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_sports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('combined', 'Combined (Primary + Secondary)'), ('tertiary', 'Tertiary/Higher Education')], max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='Has director completed initial setup?'),
        ),
        migrations.AddField(
            model_name='school',
            name='student_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
