# Generated by Django 4.2.8 on 2026-01-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_initial'),
        ('attendance', '0002_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.class'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='core.school'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='people.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='core.term'),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.teacher'),
        ),
        migrations.AddField(
            model_name='attendanceexception',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to='people.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who marked attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='people.student'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date', 'school'], name='attendance__date_fc866a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'school'], name='attendance__status_2565e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('school', 'klass', 'date', 'subject')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'status'], name='attendance__student_cb2706_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['marked_at'], name='attendance__marked__e15711_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['synced'], name='attendance__synced_d935fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'student')},
        ),
    ]
