# Generated by Django 5.0.1 on 2026-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_callback_json',
            field=models.JSONField(blank=True, default=dict, help_text='Raw M-Pesa callback data'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID from provider', max_length=100, null=True),
        ),
    ]
